name: Hata Bildirimi (Bug Report)
description: Geliştirmemize yardımcı olmak için bir rapor oluşturun
labels: ["hata", "bug"]
body:
  - type: markdown
    attributes:
      value: |
        Bu hata raporunu doldurmak için zaman ayırdığınız için teşekkürler!
  - type: textarea
    id: what-happened
    attributes:
      label: Ne oldu?
      description: Ayrıca ne olmasını beklediğinizi de söyleyin
      placeholder: Bize ne gördüğünüzü anlatın!
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Süre yazılımının hangi sürümünü kullanıyorsunuz?
      options:
        - v1.0.0
        - main
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: İlgili log çıktıları
      description: Lütfen ilgili log çıktılarını kopyalayıp yapıştırın. Bu otomatik olarak kod formatına dönüştürülecektir.
      render: shell
