name: Özellik İsteği (Feature Request)
description: Bu proje için bir fikir önerin
labels: ["geliştirme", "enhancement"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Özellik isteğiniz bir sorunla mı ilgili?
      description: Sorunun ne olduğuna dair açık ve özlü bir açıklama.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: İstediğiniz çözümü açıklayın
      description: Ne olmasını istediğinize dair açık ve özlü bir açıklama.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Düşündüğünüz alternatifleri açıklayın
      description: Düşündüğünüz alternatif çözümlerin veya özelliklerin açık ve özlü bir açıklaması.
